lm_model:
  node_lm_models:
    -
      lm_type: opt
      model_name: facebook/opt-2.7b
      node_types:
        - item
gsf:
  basic:
    backend: nccl
    verbose: false
    save_perf_results_path: null
  lm:
    cache_lm_embed: true
  gnn:
    model_encoder_type: rgcn
    fanout: "5,5"
    node_feat_name:
      - item:bert_h
    num_layers: 2
    hidden_size: 768
    use_mini_batch_infer: true
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
  hyperparam:
    dropout: 0.
    lr: 0.0001
    num_epochs: 3
    batch_size: 16
    eval_batch_size: 16
    wd_l2norm: 0.00001
    no_validation: false
  rgcn:
    num_bases: -1
    use_self_loop: true
    lp_decoder_type: dot_product
    sparse_optimizer_lr: 1e-2
    use_node_embeddings: false
  link_prediction:
    num_negative_edges: 1
    num_negative_edges_eval: 100
    target_ntype: item
    eval_etype:
      - "item,also_buy,item"
    train_etype:
      - "item,also_buy,item"
    exclude_training_targets: true
    reverse_edge_types_map: ["item,also_buy,also_buy-rev,item"]