---
version: 1.0
lm_model:
  bert_models: # bert model(s) definition, one bert model for each node type having text data
    -
      node_type: node
      model_path: /fsx-dev/xiangsx/home/workspace/M5Models/ASIN_bert_multilingual/
      gradient_checkpoint: true
gsf:
  basic:
    model_encoder_type: rgcn
    graph_name: ogbn-arxiv
    backend: nccl
    num_gpus: 4
    ip_config: ip_list.txt
    part_config: ogb_arxiv_train_val_1p_4t/ogbn-arxiv.json
    verbose: false
    use_bert_cache: false
    refresh_cache: false
    gnn_warmup_epochs: 0
    mixed_precision: false
    mp_opt_level: O2
    no_validation: false
    train_nodes: 10
    debug: false
  gnn:
    fanout: "3"
    n_layers: 1
    n_hidden: 128
    mini_batch_infer: true
  input:
    restore_model_path: null
  output:
    save_model_path: ./models/ogb_arxiv/train_val/ogb_arxiv_train_val_1p_4t_model
    save_embeds_path: null
    save_model_per_iters: 1000
  hyperparam:
    dropout: 0.
    lr: 0.001
    bert_tune_lr: 0.0001
    n_epochs: 3
    batch_size: 128
    eval_batch_size: 1024
    bert_infer_bs: 128
    wd_l2norm: 0
  rgcn:
    n_bases: -1
    use_self_loop: true
    use_dot_product: true
    self_loop_init: false
    sparse_lr: 1e-2
    use_node_embeddings: false
  link_prediction:
    num_negative_edges: 4
    num_negative_edges_eval: 100
    negative_sampler: joint
    eval_etype:
      - "node,interacts,node"
    train_etype:
      - "node,interacts,node"
    exclude_training_targets: false
    reverse_edge_types_map: []
