---
version: 1.0
gsf:
  basic:
    model_encoder_type: rgcn
    graph_name: ogbn-arxiv
    backend: gloo
    ip_config: ip_list.txt
    part_config: /data/ogbn-arxiv-1p/ogbn-arxiv.json
    verbose: false
  gnn:
    fanout: "15,10"
    n_layers: 2
    hidden_size: 128
    mini_batch_infer: false
  input:
    restore_model_path: null
  output:
    save_model_path: /data/ogbn-arxiv-1p/model/
    save_embed_path: /data/ogbn-arxiv-1p/embed/
  hyperparam:
    dropout: 0.5
    lr: 0.001
    n_epochs: 10
    batch_size: 1024
    eval_batch_size: 1024
    wd_l2norm: 0
  rgcn:
    n_bases: -1
    use_self_loop: true
    sparse_lr: 1e-2
    use_node_embeddings: false
  node_classification:
    predict_ntype: "node"
    label_field: "labels"
    multilabel: false
    num_classes: 40
