---
version: 1.0
lm_model:
  bert_models: # bert model(s) definition, one bert model for each node type having text data
    -
      node_type: node
      model_name: "allenai/scibert_scivocab_uncased"
      gradient_checkpoint: true
gsf:
  basic:
    backend: nccl
    num_gpus: 4
    ip_config: ip_list.txt
    part_config: ogb_arxiv_nc_train_val_1p_4t/ogbn-arxiv.json
    verbose: false
    debug: false
    save_perf_results_path: null
  gnn:
    model_encoder_type: rgat
    fanout: "4"
    n_layers: 1
    n_hidden: 128
    mini_batch_infer: false
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
  hyperparam:
    dropout: 0.
    lr: 0.002
    bert_tune_lr: 0.0001
    n_epochs: 3
    batch_size: 32
    eval_batch_size: 1024
    bert_infer_bs: 128
    wd_l2norm: 0
    no_validation: false
    evaluation_frequency: 100
  rgcn:
    n_bases: -1
    use_self_loop: true
    use_dot_product: true
    sparse_lr: 1e-2
    use_node_embeddings: false
  rgat:
    n_heads : 4
  node_classification:
    predict_ntype: "node"
    label_field: "labels"
    multilabel: false
    num_classes: 40
