---
version: 1.0
lm_model:
  node_lm_models:
    -
      lm_type: bert
      model_name: "bert-base-uncased"
      gradient_checkpoint: true
      node_types:
        - movie
gsf:
  basic:
    backend: gloo
    verbose: false
    save_perf_results_path: null
  lm:
    lm_train_nodes: 10
    lm_infer_batch_size: 32
    freeze_lm_encoder_epochs: 0
  gnn:
    model_encoder_type: rgcn
    fanout: "4"
    num_layers: 1
    hidden_size: 128
    use_mini_batch_infer: false
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
    save_model_frequency: 1000
  hyperparam:
    dropout: 0.
    lr: 0.001
    lm_tune_lr: 0.0001
    num_epochs: 1
    batch_size: 128
    wd_l2norm: 0
    no_validation: false
  rgcn:
    num_bases: -1
    use_self_loop: true
    sparse_optimizer_lr: 1e-2
    use_node_embeddings: false
  node_classification:
    target_ntype: "movie"
    label_field: "label"
    multilabel: false
    num_classes: 19
