---
version: 1.0
gsf:
  basic:
    backend: gloo
    ip_config: ip_list.txt
    part_config: movielen_100k_train_val_1p_4t/movie-lens-100k.json
    verbose: false
    debug: false
    save_perf_results_path: null
  gnn:
    model_encoder_type: rgcn
    fanout: "4"
    n_layers: 1
    n_hidden: 128
    mini_batch_infer: true
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
  hyperparam:
    dropout: 0.
    lr: 0.001
    lm_tune_lr: 0.0001
    n_epochs: 3
    batch_size: 128
    eval_batch_size: 1024
    bert_infer_bs: 128
    wd_l2norm: 0
    no_validation: false
  rgcn:
    n_bases: -1
    use_self_loop: true
    use_dot_product: true
    sparse_lr: 1e-2
    use_node_embeddings: false
  node_regression:
    predict_ntype: "user"
    label_field: 'age'
    eval_metric: 'mse'
