---
version: 1.0
gsf:
  basic:
    backend: gloo
    verbose: false
    save_perf_results_path: null
  gnn:
    model_encoder_type: rgcn
    fanout: "4"
    num_layers: 1
    hidden_size: 128
    use_mini_batch_infer: true
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
  hyperparam:
    dropout: 0.
    lr: 0.001
    lm_tune_lr: 0.0001
    num_epochs: 3
    batch_size: 128
    bert_infer_bs: 128
    wd_l2norm: 0
    no_validation: false
  rgcn:
    num_bases: -1
    use_self_loop: true
    sparse_optimizer_lr: 1e-2
    use_node_embeddings: false
  node_classification:
    node_feat_name:
    - movie:title
    - user:feat
    target_ntype:
    - movie
    - user
    label_field: label
    multilabel:
      movie: true
      user: true
    num_classes:
      movie: 5
      user: 5
    multilabel_weights:
      user: 0.1,0.2,0.3,0.4,0.5
    imbalance_class_weights:
      movie: 0.1,0.2,0.3,0.4,0.5
    eval_target_ntype: movie
