---
version: 1.0
gsf:
  basic:
    model_encoder_type: rgcn
    graph_name: ogbn-papers100M
    backend: gloo
    ip_config: /ip_list.txt
    part_config: null
    verbose: false
    mp_opt_level: O2
    no_validation: false
    train_nodes: 10
    debug: false
    evaluation_frequency: 500
  gnn:
    num_layers: 3
    hidden_size: 128
    use_mini_batch_infer: true
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
  hyperparam:
    dropout: 0.1
    lr: 0.001
    bert_tune_lr: 0.0001
    num_epochs: 15
    fanout: "3,5,8"
    eval_fanout: "3,5,8"
    batch_size: 1024
    eval_batch_size: 1024
    bert_infer_bs: 128
    wd_l2norm: 0
    norm: "batch"
  rgcn:
    num_bases: -1
    use_self_loop: true
    use_dot_product: true
    lp_decoder_type: dot_product
    self_loop_init: false
    sparse_optimizer_lr: 1e-2
    use_node_embeddings: false
  node_classification:
    target_ntype: "paper"
    label_field: "label"
    multilabel: false
    num_classes: 172
