---
version: 1.0
lm_model:
  bert_models: # bert model(s) definition, one bert model for each node type having text data
    -
      node_type: review
      model_name: "bert-base-uncased"
      gradient_checkpoint: true
gsf:
  basic:
    backend: gloo
    num_gpus: 4
    ip_config: ip_list.txt
    part_config: yelp_hf_1p_4t/yelp.json
    verbose: false
    debug: false
    save_perf_results_path: null
  gnn:
    model_encoder_type: rgcn
    fanout: "15"
    n_layers: 1
    n_hidden: 128
    mini_batch_infer: false
  input:
    restore_model_path: null
  output:
    save_model_path: ./models/yelp/train_val/yelp_hf_1p_4t_model
    save_embed_path: null
    save_model_per_iters: 1000
  hyperparam:
    dropout: 0.
    lr: 0.001
    bert_tune_lr: 0.0001
    n_epochs: 10
    batch_size: 256
    eval_batch_size: 10240
    bert_infer_bs: 128
    wd_l2norm: 0
  rgcn:
    n_bases: -1
    use_self_loop: true
    use_dot_product: true
    sparse_lr: 1e-2
    use_node_embeddings: false
    no_validation: false
  node_classification:
    predict_ntype: "business"
    label_field: "labels"
    multilabel: false
    num_classes: 6
