---
version: 1.0
gsf:
  basic:
    backend: gloo
    verbose: false
    save_perf_results_path: null
    batch_size: 32
    node_feat_name:
      - user:feat
      - movie:title
  gnn:
    model_encoder_type: rgcn
    num_layers: 1
    hidden_size: 32
    use_mini_batch_infer: true
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
  hyperparam:
    dropout: 0.
    lr: 0.001
    no_validation: true
  rgcn:
    num_bases: -1
    use_self_loop: true
    use_node_embeddings: false
  multi_task_learning:
    - node_classification:
        target_ntype: "movie"
        label_field: "label"
        multilabel: false
        num_classes: 19
        batch_size: 16 # will overwrite the global batch_size
        eval_metric:
          - "accuracy"
    - node_classification:
        target_ntype: "movie"
        label_field: "label2"
        multilabel: false
        num_classes: 19
        batch_size: 16 # will overwrite the global batch_size
        eval_metric:
          - "accuracy"
    - edge_classification:
        target_etype:
          - "user,rating,movie"
        label_field: "rate_class"
        multilabel: false
        num_classes: 6
        num_decoder_basis: 2
        remove_target_edge_type: false
        batch_size: 64 # will overwrite the global batch_size
    - edge_regression:
        target_etype:
          - "user,rating,movie"
        label_field: "rate"
        num_decoder_basis: 32
        remove_target_edge_type: false
    - link_prediction:
        num_negative_edges: 4
        num_negative_edges_eval: 100
        train_negative_sampler: joint
        eval_etype:
          - "user,rating,movie"
        train_etype:
          - "user,rating,movie"
        exclude_training_targets: true
        reverse_edge_types_map:
          - user,rating,rating-rev,movie
        batch_size: 128 # will overwrite the global batch_size
    - reconstruct_node_feat:
        reconstruct_nfeat_name: "title"
        target_ntype: "movie"
        batch_size: 128
        eval_metric:
          - "mse"
