---
version: 1.0
gsf:
  basic:
    model_encoder_type: rgcn
    backend: gloo
    verbose: false
  gnn:
    fanout: "20,20,20"
    num_layers: 3
    hidden_size: 128
    use_mini_batch_infer: false
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
  hyperparam:
    dropout: 0.2
    lr: 0.001
    num_epochs: 50
    batch_size: 128
    wd_l2norm: 0
  rgcn:
    num_bases: -1
    use_self_loop: true
    sparse_optimizer_lr: 1e-2
    use_node_embeddings: false
  node_classification:
    eval_metric:
      - roc_auc
    target_ntype: "super"
    label_field: "labels"
    multilabel: false
    num_classes: 2
