---
version: 1.0
gsf:
  basic:
    backend: gloo
    verbose: false
    save_perf_results_path: null
  gnn:
    model_encoder_type: sage
    fanout: "4"
    num_layers: 1
    hidden_size: 128
    use_mini_batch_infer: true
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
  hyperparam:
    dropout: 0.
    lr: 0.001
    lm_tune_lr: 0.0001
    num_epochs: 3
    batch_size: 64
    wd_l2norm: 0
    no_validation: false
    eval_frequency: 1000
  rgcn:
    num_bases: -1
    use_self_loop: true
    sparse_optimizer_lr: 1e-2
    use_node_embeddings: false
  edge_classification:
    label_field: "rate"
    multilabel: false
    num_classes: 5
    num_decoder_basis: 32
    exclude_training_targets: false
