---
version: 1.0
gsf:
  basic:
    backend: gloo
    ip_config: ip_list.txt
    part_config: movielen_100k_er_1p_4t/movie-lens-100k.json
    verbose: false
    save_perf_results_path: null
  gnn:
    model_encoder_type: rgcn
    fanout: "4"
    num_layers: 1
    hidden_size: 128
    use_mini_batch_infer: true
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
  hyperparam:
    dropout: 0.
    lr: 0.001
    lm_tune_lr: 0.0001
    num_epochs: 3
    batch_size: 64
    wd_l2norm: 0
    no_validation: false
    eval_frequency: 1000
  rgcn:
    num_bases: -1
    use_self_loop: true
    sparse_optimizer_lr: 1e-2
    use_node_embeddings: false
  edge_regression:
    target_etype:
      - "user,rating,movie"
    reverse_edge_types_map:
      - "user,rating,rating-rev,movie"
    label_field: "rate"
    num_decoder_basis: 32
    exclude_training_targets: True
