---
version: 1.0
lm_model:
  bert_models: # bert model(s) definition, one bert model for each node type having text data
    -
      node_type: movie
      model_name: "bert-base-uncased"
      gradient_checkpoint: true
    -
      node_type: user
      model_name: "bert-base-uncased"
      gradient_checkpoint: true
gsf:
  basic:
    model_encoder_type: rgcn
    graph_name: movie-lens-100k
    backend: gloo
    num_gpus: 4
    ip_config: ip_list.txt
    part_config: movielen_100k_utext_train_val_1p_4t/movie-lens-100k.json
    verbose: false
    gnn_warmup_epochs: 0
    mixed_precision: false
    no_validation: false
    train_nodes: 10
    debug: false
  gnn:
    fanout: "4"
    n_layers: 1
    n_hidden: 128
    mini_batch_infer: true
  input:
    restore_model_path: null
  output:
    save_model_path: ./models/movielen_100k/train_val/movielen_100k_utext_train_val_1p_4t_model
    save_embeds_path: null
    save_model_per_iters: 1000
  hyperparam:
    dropout: 0.
    lr: 0.001
    bert_tune_lr: 0.0001
    n_epochs: 3
    batch_size: 128
    eval_batch_size: 1024
    bert_infer_bs: 128
    wd_l2norm: 0
  rgcn:
    n_bases: -1
    use_self_loop: true
    use_dot_product: true
    sparse_lr: 1e-2
    use_node_embeddings: false
  node_classification:
    predict_ntype: "movie"
    label_field: "genre"
    multilabel: false
    num_classes: 19
