name: submit job to AWS Batch
inputs:
  command:
    job-type: true
    job-name: 
    required: true

# installing dependencies and configuring AWS Credentials
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::698571788627:role/github-oidc-role
        aws-region: us-east-1
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install boto3
    - name: Submit Job (for Push)
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: |
        echo "Start submitting job - Push"
        python3 ./submitJob.py --job-type ${{ inputs.job-type }}-PUSH --name ${{ inputs.job-name }}-Push-'${{ github.ref }}' --command "${{ inputs.command }}" --wait
    - name: Submit Job (for Pull Request)
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        echo "Start submitting job - Pull Request"
        python3 ./submitJob.py --job-type ${{ inputs.job-type }} --name ${{ inputs.job-name }}-PR#-'${{ github.event.number }}' --command "${{ inputs.command }}" --wait    