---
version: 1.0
lm_model:
  node_lm_models:
    -
      lm_type: bert
      model_name: "bert-base-uncased"
      gradient_checkpoint: false
      node_types:
        - paper
        - author
        - subject
gsf:
  basic:
    backend: gloo
    verbose: false
  lmgnn:
    lm_train_nodes: 256
    lm_infer_batch_size: 256
    freeze_lm_encoder_epochs: 0
    model_encoder_type: rgcn
    fanout: "50,50"
    num_layers: 2
    hidden_size: 256
    use_mini_batch_infer: false
    training_method:
      name: glem
      kwargs:
        em_order_gnn_first: false
        inference_using_gnn: true
        pl_weight: 0.5
        num_pretrain_epochs: 100
    use_pseudolabel: true
  input:
    restore_model_path: null
  output:
    save_model_path: /tmp/acm_nc/models
    save_embeds_path: /tmp/acm_nc/embeds
  hyperparam:
    dropout: 0.
    lr: 0.0001
    lm_tune_lr: 0.0001
    num_epochs: 300
    batch_size: 1024
    wd_l2norm: 0
    alpha_l2norm: 0.
    no_validation: false
  rgcn:
    num_bases: -1
    use_self_loop: true
    sparse_optimizer_lr: 1e-2
    use_node_embeddings: false
  node_classification:
    target_ntype: "paper"
    label_field: "label"
    multilabel: false
    num_classes: 14
