---
version: 1.0
gsf:
  basic:
    model_encoder_type: rgcn
    backend: gloo
    ip_config: ip_list.txt
    part_config: /data/acm_nc/acm.json
    verbose: false
    no_validation: false
    alpha_l2norm: 0.
  gnn:
    fanout: "50,50"
    num_layers: 2
    hidden_size: 256
    use_mini_batch_infer: false
  input:
    restore_model_path: null
  output:
    save_model_path: /data/outputs
    save_embeds_path: /data/outputs
  hyperparam:
    dropout: 0.
    lr: 0.0001
    lm_tune_lr: 0.0001
    num_epochs: 200
    batch_size: 1024
    bert_infer_bs: 128
    wd_l2norm: 0
  rgcn:
    num_bases: -1
    use_self_loop: true
    sparse_optimizer_lr: 1e-2
    use_node_embeddings: false
  node_classification:
    target_ntype: "paper"
    label_field: "label"
    multilabel: false
    num_classes: 14
