---
version: 1.0
gsf:
  basic:
    model_encoder_type: rgcn
    backend: gloo
    num_gpus: 4
    verbose: false
  gnn:
    fanout: "3"
    n_layers: 1
    n_hidden: 128
    mini_batch_infer: true
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
    save_model_per_iters: 1000
  hyperparam:
    dropout: 0.
    lr: 0.001
    bert_tune_lr: 0.0001
    num_epochs: 3
    batch_size: 128
    eval_batch_size: 1024
    wd_l2norm: 0
    no_validation: false
  rgcn:
    n_bases: -1
    use_self_loop: true
    lp_decoder_type: "dot_product"
    sparse_optimizer_lr: 1e-2
    use_node_embeddings: false
  link_prediction:
    num_negative_edges: 4
    num_negative_edges_eval: 100
    train_negative_sampler: joint
    eval_etype:
      - "node,interacts,node"
    train_etype:
      - "node,interacts,node"
    exclude_training_targets: false
    reverse_edge_types_map: []
