---
version: 1.0
lm_model:
  node_lm_models:
    -
      lm_type: bert
      model_name: "bert-base-uncased"
      gradient_checkpoint: true
      node_types:
        - movie
gsf:
  basic:
    backend: gloo
    ip_config: ip_list.txt
    part_config: movielen_100k_lp_user_feat_movie_token_1p/ml.json
    verbose: false
    save_perf_results_path: null
  gnn:
    model_encoder_type: mlp
    hidden_size: 128
    use_mini_batch_infer: true
  lm:
    lm_train_nodes: 10
    lm_infer_batch_size: 32
    freeze_lm_encoder_epochs: 0
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
  hyperparam:
    dropout: 0.
    lr: 0.001
    lm_tune_lr: 0.0001
    num_epochs: 3
    batch_size: 128
    wd_l2norm: 0
    no_validation: false
  link_prediction:
    num_negative_edges: 4
    num_negative_edges_eval: 100
    train_negative_sampler: joint
    eval_etype:
      - "user,rating,movie"
    train_etype:
      - "user,rating,movie"
    exclude_training_targets: false
    reverse_edge_types_map: []
