---
version: 1.0
gsf:
  basic:
    backend: gloo
    verbose: false
    save_perf_results_path: null
  gnn:
    model_encoder_type: rgcn
    fanout: "4"
    num_layers: 1
    hidden_size: 128
    use_mini_batch_infer: true
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
  hyperparam:
    dropout: 0.
    lr: 0.001
    lm_tune_lr: 0.0001
    num_epochs: 3
    batch_size: 128
    wd_l2norm: 0
    no_validation: false
  rgcn:
    num_bases: -1
    use_self_loop: true
    lp_decoder_type: dot_product
    sparse_optimizer_lr: 1e-2
    use_node_embeddings: false
  link_prediction:
    num_negative_edges: 4
    num_negative_edges_eval: 100
    train_negative_sampler: joint
    eval_etype:
      - "user,rating,movie"
    train_etype:
      - "user,rating,movie"
    exclude_training_targets: false
    reverse_edge_types_map: []
