---
version: 1.0
lm_model:
  node_lm_models:
    -
      lm_type: bert
      model_name: "bert-base-uncased"
      gradient_checkpoint: true
      node_types:
        - movie
        - user
gsf:
  basic:
    backend: gloo
    ip_config: ip_list.txt
    part_config: movielen_100k_er_1p_4t/movie-lens-100k.json
    verbose: false
    debug: false
  lm:
    lm_infer_batchszie: 32
  gnn:
    model_encoder_type: rgcn
    fanout: "4"
    n_layers: 1
    n_hidden: 128
    mini_batch_infer: true
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
  hyperparam:
    batch_size: 64
    eval_batch_size: 1024
    bert_infer_bs: 128
    no_validation: false
  rgcn:
    n_bases: -1
    use_self_loop: true
    use_dot_product: true
    use_node_embeddings: false
  edge_classification:
    target_etype:
      - "user,rating,movie"
    label_field: "rate"
    num_decoder_basis: 32
    reverse_edge_types_map: []
    multilabel: false
    exclude_training_targets: false
    num_classes: 6
