
# Graphstorm CI
# Test execution order - [lint] -> [pytest] -> [end2end_cpu, end2end, end2end_mgpu]
name: continuous-integration

on:
  push:
    branches:
      - main
      - ci_dev
    paths-ignore:
      - '.github/workflow_scripts/gsprocessing_pytest.sh'
      - '.github/workflow_scripts/gsprocessing_lint.sh'
      - 'graphstorm-processing/**'
      - '.github/workflows/gsprocessing-workflow.yml'
      - 'docs/**'
  pull_request_target:
    types: [ labeled ]
    paths-ignore:
      - '.github/workflow_scripts/gsprocessing_pytest.sh'
      - '.github/workflow_scripts/gsprocessing_lint.sh'
      - 'graphstorm-processing/**'
      - '.github/workflows/gsprocessing-workflow.yml'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.event.pull_request.head.sha }}
  cancel-in-progress: true

permissions:
  id-token: write
  pull-requests: write
  contents: read

defaults:
  run:
    shell: bash

# All test scripts split in individual .sh files and moved to .github/workflow_scripts
env:
  COMMAND-PYTEST: chmod +x ./pytest_check.sh && ./pytest_check.sh
  COMMAND-LINT: chmod +x ./lint_check.sh && ./lint_check.sh
  COMMAND-E2E-CPU-TEST: chmod +x ./e2e_cpu_check.sh && ./e2e_cpu_check.sh
  COMMAND-E2E: chmod +x ./e2e_check.sh && ./e2e_check.sh
  COMMAND-E2E-MGPU: chmod +x ./e2e_mgpu_check.sh && ./e2e_mgpu_check.sh
  COMMAND-E2E-MGPU-MULTITASK: chmod +x ./e2e_mgpu_multitask_check.sh && ./e2e_mgpu_multitask_check.sh
  COMMAND-E2E-GB: chmod +x ./e2e_gb_check.sh && ./e2e_gb_check.sh

jobs:

  # ─────────────────────────────────────────────────────────────────────────────
  # LINT CHECK
  # ─────────────────────────────────────────────────────────────────────────────
  lint_check:
    if: ${{ github.event_name == 'push' ||
      (github.event_name == 'pull_request_target'
      && github.event.action == 'labeled'
      && github.event.label.name == 'ready') }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::698571788627:role/github-oidc-role
          role-duration-seconds: 14400
          aws-region: us-east-1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          pip3 install boto3

      - name: Submit Job (for Push)
        if: ${{ github.event_name == 'push' }}
        env:
          GIT_REF: ${{ github.ref }}
          LINT_COMMAND: ${{ env.COMMAND-LINT }}
          REPO_NAME: ${{ github.repository }}
        run: |
          echo "Start submitting job - Push"
          python3 ./submitJob.py --job-type CI-LINT-PUSH \
                                 --name "Graphstorm-LintTest-Push-${GIT_REF}" \
                                 --command "${LINT_COMMAND}" \
                                 --remote "https://github.com/${REPO_NAME}" \
                                 --source-ref "${GIT_REF}" \
                                 --wait

      - name: Submit Job (for Pull Request)
        if: ${{ github.event_name == 'pull_request_target' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
          LINT_COMMAND: ${{ env.COMMAND-LINT }}
          PR_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "Start submitting job - Pull Request"
          python3 ./submitJob.py --job-type CI-LINT-PUSH \
                                 --name "Graphstorm-LintTest-PR#-${PR_NUMBER}" \
                                 --command "${LINT_COMMAND}" \
                                 --remote "https://github.com/${PR_REPO}" \
                                 --source-ref "${PR_SHA}" \
                                 --wait

  # ─────────────────────────────────────────────────────────────────────────────
  # PYTEST CHECK
  # ─────────────────────────────────────────────────────────────────────────────
  pytest_check:
    if: ${{ github.event_name == 'push' ||
      (github.event_name == 'pull_request_target'
      && github.event.action == 'labeled'
      && github.event.label.name == 'ready') }}
    needs: lint_check
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::698571788627:role/github-oidc-role
          aws-region: us-east-1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          pip3 install boto3

      - name: Submit Job (for Push)
        if: ${{ github.event_name == 'push' }}
        env:
          GIT_REF: ${{ github.ref }}
          PYTEST_COMMAND: ${{ env.COMMAND-PYTEST }}
          REPO_NAME: ${{ github.repository }}
        run: |
          echo "Start submitting job - Push"
          python3 ./submitJob.py --job-type CI-CPU-PUSH \
                                 --name "Graphstorm-PyTest-Push-${GIT_REF}" \
                                 --command "${PYTEST_COMMAND}" \
                                 --remote "https://github.com/${REPO_NAME}" \
                                 --source-ref "${GIT_REF}" \
                                 --wait

      - name: Submit Job (for Pull Request)
        if: ${{ github.event_name == 'pull_request_target' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
          PYTEST_COMMAND: ${{ env.COMMAND-PYTEST }}
          PR_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "Start submitting job - Pull Request"
          python3 ./submitJob.py --job-type CI-CPU \
                                 --name "Graphstorm-PyTest-PR#-${PR_NUMBER}" \
                                 --command "${PYTEST_COMMAND}" \
                                 --remote "https://github.com/${PR_REPO}" \
                                 --source-ref "${PR_SHA}" \
                                 --wait

  # ─────────────────────────────────────────────────────────────────────────────
  # END-TO-END CPU CHECK
  # ─────────────────────────────────────────────────────────────────────────────
  e2e_cpu_check:
    if: ${{ github.event_name == 'push' ||
      (github.event_name == 'pull_request_target'
      && github.event.action == 'labeled'
      && github.event.label.name == 'ready') }}
    needs: [pytest_check, lint_check]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::698571788627:role/github-oidc-role
          aws-region: us-east-1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          pip3 install boto3

      - name: Submit Job (for Push)
        if: ${{ github.event_name == 'push' }}
        env:
          GIT_REF: ${{ github.ref }}
          E2E_CPU_COMMAND: ${{ env.COMMAND-E2E-CPU-TEST }}
          REPO_NAME: ${{ github.repository }}
        run: |
          echo "Start submitting job - Push"
          python3 ./submitJob.py --job-type CI-CPU-CHECK-PUSH \
                                 --name "Graphstorm-E2ETest-CPU-Push-${GIT_REF}" \
                                 --command "${E2E_CPU_COMMAND}" \
                                 --remote "https://github.com/${REPO_NAME}" \
                                 --source-ref "${GIT_REF}" \
                                 --wait

      - name: Submit Job (for Pull Request)
        if: ${{ github.event_name == 'pull_request_target' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
          E2E_CPU_COMMAND: ${{ env.COMMAND-E2E-CPU-TEST }}
          PR_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "Start submitting job - Pull Request"
          python3 ./submitJob.py --job-type CI-CPU-CHECK \
                                 --name "Graphstorm-E2ETest-CPU-PR#-${PR_NUMBER}" \
                                 --command "${E2E_CPU_COMMAND}" \
                                 --remote "https://github.com/${PR_REPO}" \
                                 --source-ref "${PR_SHA}" \
                                 --wait

  # ─────────────────────────────────────────────────────────────────────────────
  # END-TO-END CHECK (GPU)
  # ─────────────────────────────────────────────────────────────────────────────
  e2e_check:
    if: ${{ github.event_name == 'push' ||
      (github.event_name == 'pull_request_target'
      && github.event.action == 'labeled'
      && github.event.label.name == 'ready') }}
    needs: [pytest_check, lint_check]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::698571788627:role/github-oidc-role
          role-duration-seconds: 14400
          aws-region: us-east-1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          pip3 install boto3

      - name: Submit Job (for Push)
        if: ${{ github.event_name == 'push' }}
        env:
          GIT_REF: ${{ github.ref }}
          E2E_COMMAND: ${{ env.COMMAND-E2E }}
          REPO_NAME: ${{ github.repository }}
        run: |
          echo "Start submitting job - Push"
          python3 ./submitJob.py --job-type CI-CPU-PUSH \
                                 --name "Graphstorm-E2ETest-Push-${GIT_REF}" \
                                 --command "${E2E_COMMAND}" \
                                 --remote "https://github.com/${REPO_NAME}" \
                                 --source-ref "${GIT_REF}" \
                                 --wait

      - name: Submit Job (for Pull Request)
        if: ${{ github.event_name == 'pull_request_target' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
          E2E_COMMAND: ${{ env.COMMAND-E2E }}
          PR_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "Start submitting job - Pull Request"
          python3 ./submitJob.py --job-type CI-CPU \
                                 --name "Graphstorm-E2ETest-PR#-${PR_NUMBER}" \
                                 --command "${E2E_COMMAND}" \
                                 --remote "https://github.com/${PR_REPO}" \
                                 --source-ref "${PR_SHA}" \
                                 --wait

  # ─────────────────────────────────────────────────────────────────────────────
  # END-TO-END MULTI-GPU CHECK
  # ─────────────────────────────────────────────────────────────────────────────
  e2e_mgpu_check:
    if: ${{ github.event_name == 'push' ||
      (github.event_name == 'pull_request_target'
      && github.event.action == 'labeled'
      && github.event.label.name == 'ready') }}
    needs: [pytest_check, lint_check]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::698571788627:role/github-oidc-role
          aws-region: us-east-1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          pip3 install boto3

      - name: Submit Job (for Push)
        if: ${{ github.event_name == 'push' }}
        env:
          GIT_REF: ${{ github.ref }}
          E2E_MGPU_COMMAND: ${{ env.COMMAND-E2E-MGPU }}
          REPO_NAME: ${{ github.repository }}
        run: |
          echo "Start submitting job - Push"
          python3 ./submitJob.py --job-type CI-GPU-PUSH \
                                 --name "Graphstorm-E2E-MGPUTest-Push-${GIT_REF}" \
                                 --command "${E2E_MGPU_COMMAND}" \
                                 --remote "https://github.com/${REPO_NAME}" \
                                 --source-ref "${GIT_REF}" \
                                 --wait

      - name: Submit Job (for Pull Request)
        if: ${{ github.event_name == 'pull_request_target' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
          E2E_MGPU_COMMAND: ${{ env.COMMAND-E2E-MGPU }}
          PR_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "Start submitting job - Pull Request"
          python3 ./submitJob.py --job-type CI-GPU \
                                 --name "Graphstorm-E2E-MGPUTest-PR#-${PR_NUMBER}" \
                                 --command "${E2E_MGPU_COMMAND}" \
                                 --remote "https://github.com/${PR_REPO}" \
                                 --source-ref "${PR_SHA}" \
                                 --wait

  # ─────────────────────────────────────────────────────────────────────────────
  # END-TO-END MULTI-GPU MULTITASK CHECK
  # ─────────────────────────────────────────────────────────────────────────────
  e2e_mgpu_check_multitask:
    if: ${{ github.event_name == 'push' ||
      (github.event_name == 'pull_request_target'
      && github.event.action == 'labeled'
      && github.event.label.name == 'ready') }}
    needs: [pytest_check, lint_check]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::698571788627:role/github-oidc-role
          aws-region: us-east-1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          pip3 install boto3

      - name: Submit Job (for Push)
        if: ${{ github.event_name == 'push' }}
        env:
          GIT_REF: ${{ github.ref }}
          E2E_MGPU_MT_COMMAND: ${{ env.COMMAND-E2E-MGPU-MULTITASK }}
          REPO_NAME: ${{ github.repository }}
        run: |
          echo "Start submitting job - Push"
          python3 ./submitJob.py --job-type CI-GPU-PUSH \
                                 --name "Graphstorm-E2E-MGPUTest-MultiTask-Push-${GIT_REF}" \
                                 --command "${E2E_MGPU_MT_COMMAND}" \
                                 --remote "https://github.com/${REPO_NAME}" \
                                 --source-ref "${GIT_REF}" \
                                 --wait

      - name: Submit Job (for Pull Request)
        if: ${{ github.event_name == 'pull_request_target' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
          E2E_MGPU_MT_COMMAND: ${{ env.COMMAND-E2E-MGPU-MULTITASK }}
          PR_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "Start submitting job - Pull Request"
          python3 ./submitJob.py --job-type CI-GPU \
                                 --name "Graphstorm-E2E-MGPUTest-MultiTask-PR#-${PR_NUMBER}" \
                                 --command "${E2E_MGPU_MT_COMMAND}" \
                                 --remote "https://github.com/${PR_REPO}" \
                                 --source-ref "${PR_SHA}" \
                                 --wait

  # ─────────────────────────────────────────────────────────────────────────────
  # END-TO-END GRAPHBOLT CHECK
  # ─────────────────────────────────────────────────────────────────────────────
  e2e_graphbolt:
    if: ${{ github.event_name == 'push' ||
      (github.event_name == 'pull_request_target'
      && github.event.action == 'labeled'
      && github.event.label.name == 'ready') }}
    needs: [pytest_check, lint_check]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::698571788627:role/github-oidc-role
          aws-region: us-east-1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          pip3 install boto3

      - name: Submit Job (for Push)
        if: ${{ github.event_name == 'push' }}
        env:
          GIT_REF: ${{ github.ref }}
          E2E_GB_COMMAND: ${{ env.COMMAND-E2E-GB }}
          REPO_NAME: ${{ github.repository }}
        run: |
          echo "Start submitting job - Push"
          python3 ./submitJob.py --job-type CI-GPU-DGL230 \
                                 --name "Graphstorm-E2E-Test-GB-Push-${GIT_REF}" \
                                 --command "${E2E_GB_COMMAND}" \
                                 --remote "https://github.com/${REPO_NAME}" \
                                 --source-ref "${GIT_REF}" \
                                 --wait

      - name: Submit Job (for Pull Request)
        if: ${{ github.event_name == 'pull_request_target' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
          E2E_GB_COMMAND: ${{ env.COMMAND-E2E-GB }}
          PR_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "Start submitting job - Pull Request"
          python3 ./submitJob.py --job-type CI-GPU-DGL230 \
                                 --name "Graphstorm-E2E-Test-GB-PR#-${PR_NUMBER}" \
                                 --command "${E2E_GB_COMMAND}" \
                                 --remote "https://github.com/${PR_REPO}" \
                                 --source-ref "${PR_SHA}" \
                                 --wait

  # ─────────────────────────────────────────────────────────────────────────────
  # AUTO-REMOVE 'ready' LABEL
  # Ensures the maintainer must re-apply it to trigger another run.
  # always() ensures the label is removed even when upstream jobs fail.
  # ─────────────────────────────────────────────────────────────────────────────
  remove_ready_label:
    needs: [lint_check, pytest_check, e2e_cpu_check, e2e_check,
            e2e_mgpu_check, e2e_mgpu_check_multitask, e2e_graphbolt]
    if: ${{ always()
      && github.event_name == 'pull_request_target'
      && github.event.action == 'labeled'
      && github.event.label.name == 'ready' }}
    runs-on: ubuntu-latest
    steps:
      - name: Remove 'ready' label
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'ready'
            }).catch(err => { if (err.status !== 404) throw err; });

