# Graphstorm CI for GSProcessing Only
# Test execution order - [lint] -> [pytest]
name: gsprocessing_workflow

on:
  push:
    branches:
      - main
      - ci_dev
    paths:
      - '.github/workflow_scripts/gsprocessing.sh'
      - 'graphstorm-processing/*'
    workflow_dispatch:
  pull_request_target:
    paths:
      - '.github/workflow_scripts/gsprocessing.sh'
      - 'graphstorm-processing/*'

permissions:
  id-token: write
  pull-requests: write
  contents: read

defaults:
  run:
    shell: bash

# All test scripts split in individual .sh files and moved to .github/workflow scripts
env:
  COMMAND-LINT: chmod +x ./lint_check.sh && ./lint_check.sh
  COMMAND-GSProcessing: chmod +x ./gsprocessing.sh && ./gsprocessing.sh

jobs:
  lint_check:
    if: ${{ github.event.label.name != 'draft' }}
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::698571788627:role/github-oidc-role
        aws-region: us-east-1
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pytest
        pip3 install boto3
    - name: Submit Job (for Push)
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: |
        echo "Start submitting job - Push hahaha"  
        python3 ./submitJob.py --job-type CI-LINT-PUSH --name Graphstorm-LintTest-Push-'${{ github.ref }}' \
                               --command "${{ env.COMMAND-LINT }}" \
                               --remote https://github.com/'${{ github.repository }}' \
                               --source-ref '${{ github.ref }}' \
                               --wait
    - name: Submit Job (for Pull Request)
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        echo "Start submitting job - Pull Request"
        python3 ./submitJob.py --job-type CI-LINT-PUSH --name Graphstorm-LintTest-PR#-'${{ github.event.number }}' \
                               --command "${{ env.COMMAND-LINT }}" \
                               --remote https://github.com/'${{ github.event.pull_request.head.repo.full_name }}' \
                               --source-ref '${{ github.event.pull_request.head.sha }}' \
                               --wait

  gsprocessing:
    if: ${{ github.event.label.name != 'draft' }}
    needs: lint_check
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::698571788627:role/github-oidc-role
        aws-region: us-east-1
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pytest
        pip3 install boto3
    - name: Submit Job (for Push)
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: |
        echo "Start submitting job - Push"  
        python3 ./submitJob.py --job-type CI-GSProcessing-CHECK --name Graphstorm-GSProcessing-Push-'${{ github.ref }}' \
                               --command "${{ env.COMMAND-GSProcessing }}" \
                               --remote https://github.com/'${{ github.repository }}' \
                               --source-ref '${{ github.ref }}' \
                               --wait
    - name: Submit Job (for Pull Request)
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        echo "Start submitting job - Pull Request"
        python3 ./submitJob.py --job-type CI-GSProcessing-CHECK --name Graphstorm-GSProcessing-PR#-'${{ github.event.number }}' \
                               --command "${{ env.COMMAND-GSProcessing }}" \
                               --remote https://github.com/'${{ github.event.pull_request.head.repo.full_name }}' \
                               --source-ref '${{ github.event.pull_request.head.sha }}' \
                               --wait
  
