# Name of this GitHub Actions workflow.
name: semgrep-scan

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan mainline branches and report all findings: 
  push:
    branches: ["ci_dev", "ci_temporary"]
  schedule:
    - cron: '*/5 * * * *' 

defaults:
  run:
    shell: bash

jobs:
  semgrep:
    
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Semgrep
        run: |
          pip install semgrep
          semgrep --version
      
      - name: Directory
        run: pwd

      # Period (.) to run scan in the current directory 
      - name: Run Scan - 1 (Default Ruleset)
        run: semgrep --config=p/default . --exclude=+BLOCKING
      
      
      - name: Run Scan - 2 (Ruleset for python)
        run: semgrep --config=p/python . --exclude=+BLOCKING
      
      # - name: Run Scan - 3
      #   run: semgrep ci
      #   env:
      #      # Add the rules that Semgrep uses by setting the SEMGREP_RULES environment variable. 
      #      SEMGREP_RULES: p/default p/python p/owasp-top-ten